class SavingAccount(): ...


class ChekingAccount(): ...


class Stock(): ...


class Bond(): ...


class RealEstate(): ...


class BankAccount(SavingAccount, ChekingAccount): ...


class Security(Stock, Bond): ...


class InterBearingitem(BankAccount, Security): ...


class asset(BankAccount, Security, RealEstate): ...


class Insurableitem(BankAccount, RealEstate): ...

print(BankAccount.mro(),Security.mro(),InterBearingitem.mro,asset.mro,Insurableitem.mro)
